### ISSUE TITLE
Add 'brief' support

### ISSUE THREAD

**Issue by nckrse** [CumulusNetworks/iproute2#1]
I noticed that the Cumulus VX release has a "-br" or "-brief" switch to pretty the output. Will it be added this iproute2 repo?

cumulus@cumulus$ ip --help
Usage: ip [ OPTIONS ] OBJECT { COMMAND | help }
       ip [ -force ] -batch filename
where  OBJECT := { link | addr | addrlabel | route | rule | neigh | ntable |
                   tunnel | tuntap | maddr | mroute | mrule | monitor | xfrm |
                   netns | l2tp }
       OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] | -r[esolve] |
                    -f[amily] { inet | inet6 | ipx | dnet | link } |
                    -l[oops] { maximum-addr-flush-attempts } |
                    -o[neline] | -br[ief] | -t[imestamp] | -b[atch] [filename] |
                    -rc[vbuf] [size]}
cumulus@cumulus$ ip -brief link show
lo           UNKNOWN  00:00:00:00:00:00  <LOOPBACK,UP,LOWER_UP>
eth0         UP       08:00:27:55:42:8d  <BROADCAST,MULTICAST,UP,LOWER_UP>
swp1         DOWN     08:00:27:72:9b:d3  <BROADCAST,MULTICAST>
swp2         DOWN     08:00:27:47:a6:e8  <BROADCAST,MULTICAST>
cumulus@cumulus$ ip -brief addr show
lo           UNKNOWN  127.0.0.1/8 ::1/128
eth0         UP       10.0.2.15/24 fe80::a00:27ff:fe55:428d/64
swp1         DOWN
swp2         DOWN
cumulus@cumulus$

**Comment by gospo** [comment]
Rather than only here, we will look at pushing it upstream first.

**Comment by gospo** [comment]
Support for this output was added to upstream iproute2.

https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git/commit/?id=5d295bb8e1af491bc3de1d2506cbb2bd6bbd9da1

The source for it will be added here next time it is rebased to the upstream version of iproute2.
